# Parameters
FIXED_STEP_DURATION = 0.1  # Each step is 0.2 seconds
MAX_CREATURES = 50
MAX_ENERGY_CAPACITY = 200
MIN_ENERGY_CAPACITY = 1
GENERAL_ENERGY_CONSUMPTION = 10
GENERAL_ENERGY_PRODUCTION = 10
CREATURE_SIZE_MAX = 10  # Creature size
CREATURE_SIZE_MIN = 5  # Creature size
MUTATION_RATE = 0.1  # Mutation rate
MATURITY_LEVEL_MAX = 20
MATURITY_LEVEL_MIN = 5
AGING_LEVEL_STARTS = MATURITY_LEVEL_MAX * 3

CONSUMPTION_RATE_MAX = 1
CONSUMPTION_RATE_MIN = 0

PRODUCTION_RATE_MAX = 1
PRODUCTION_RATE_MIN = 0

# Action Zone Ratio Parameters
ACTION_ZONE_RATIO_MAX = 1
ACTION_ZONE_RATIO_MIN = 0
ACTION_ZONE_MAX = CREATURE_SIZE_MAX * 3

# Screen dimensions
WIDTH, HEIGHT = 400, 300

PLOT_PAUSE = 0.2
