# Parameters
FIXED_STEP_DURATION = 0.1  # Each step is 0.2 seconds
MAX_CREATURES = 100
MAX_ENERGY_CAPACITY = 200
MIN_ENERGY_CAPACITY = 1
GENERAL_ENERGY_CONSUMPTION = 10
GENERAL_ENERGY_PRODUCTION = 10
CREATURE_SIZE_MAX = 10  # Creature size
CREATURE_SIZE_MIN = 5  # Creature size
MUTATION_RATE = 0.1  # Mutation rate
MATURITY_LEVEL_MAX = 20
MATURITY_LEVEL_MIN = 5

CONSUMPTION_RATE_MAX = 1
CONSUMPTION_RATE_MIN = 0

PRODUCTION_RATE_MAX = 1
PRODUCTION_RATE_MIN = 0


# Screen dimensions
WIDTH, HEIGHT = 300, 300

PLOT_PAUSE = 0.2